export const ads = [
    {
        id: 1,
        name: "IPhone X",
        price: 49000,
        cat: "mobile",
        location: "G-10",
        city: "Islamabad",
        imgSrc: "https://starcity.pk/wp-content/uploads/2022/08/Iphone-x-2-1.jpg",
    },
    {
        id: 2,
        name: "IPhone 15",
        price: 150000,
        cat: "mobile",
        location: "Touch Me Chowrangi",
        city: "Karachi",
        imgSrc: "https://static0.pocketlintimages.com/wordpress/wp-content/uploads/wm/2023/09/iphone-15-pro-max-review-4-1.jpg?w=1600&h=900&fit=crop",
    },
    {
        id: 3,
        name: "1 Kanal House DHA Phase 2",
        price: "2.5cr",
        cat: "house",
        location: "DHA Phase 2 Block B",
        city: "Islamabad",
        imgSrc: "https://www.livehome3d.com/assets/img/social/how-to-design-a-house.jpg",
    },
    {
        id: 4,
        name: "2 Kanal House Bahria Town Phase 3",
        price: "5.5cr",
        cat: "house",
        location: "Bahria Town Phase 3",
        city: "Islamabad",
        imgSrc: "https://thermohouse.ie/wp-content/uploads/2019/04/hero-image.jpg",
    },
    {
        id: 5,
        name: "2 Kanal House Bahria Town Phase 3",
        price: "10.8cr",
        cat: "house",
        location: "Bahria Town Phase 2",
        city: "Islamabad",
        imgSrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpui9mvz_xElG51fD0sxPOZ8EtIQzv0s2Lxw&s",
    },
    {
        id: 6,
        name: "Toyota Land Cruiser LC300 ZX 2022",
        price: "6.5cr",
        cat: "car",
        location: "Johar Town",
        city: "Lahore",
        imgSrc: "https://lh3.googleusercontent.com/proxy/03-8uv6kYl6g3TARb2Ied1Se05RK1K_JGJ8sO_XG2Fd-fv00YwZLTaL-ThqgJ-uR7VjMtLYEwXTnZLojPbSej4BsbL9UZX_URqG2k9biTUKlWqJdTiOHPMC-jXJvRg_rwQNjclA61RETMTe4H-xMpI34_rNneZQ02P2u-qrFrYPZR72QuVusOmg",
    },
    {
        id: 7,
        name: "Mazda RX7 Rocket Bunny",
        price: "1.8cr",
        cat: "car",
        location: "F-7",
        city: "Islamabad",
        imgSrc: "https://scontent.fpew3-1.fna.fbcdn.net/v/t51.75761-15/488492610_18453075934075561_6553391370000354483_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=127cfc&_nc_ohc=_EVVOtN0eakQ7kNvwHwURkN&_nc_oc=Adm3x9a0Qs5-TWeWiemVIYtULdsSEh9HSI3bK0dCcPUgWwE97Hgsklhq3BQNOSQx1ss&_nc_zt=23&_nc_ht=scontent.fpew3-1.fna&_nc_gid=Q5n8b-eqV09U1Deey5iQAQ&oh=00_Afv5j1kZRCigBSbFQvgIJOf5t8PYTvm24rC5a_dhbIsI5A&oe=698D75BA",
    },
    {
        id: 8,
        name: "Mercedes Benz E63 AMG W211",
        price: "1.2cr",
        cat: "car",
        location: "Bahadurabad",
        city: "Karachi",
        imgSrc: "https://i.redd.it/6vuc9wtdc11b1.jpg",
    },
    {
        id: 9,
        name: "2 Bedrooms For Rent",
        price: "64,000",
        cat: "house",
        location: "Park View City",
        city: "Islamabad",
        imgSrc: "https://www.smartcitypk.com/assets/uploads/villas_5e621fbc1d250.png",
    },
    {
        id: 10,
        name: "Custom Furniture",
        price: "120,000",
        cat: "furniture",
        location: "Gulshan-e-Iqbal",
        city: "Lahore",
        imgSrc: "https://birchwoodfurniture.ca/wp-content/uploads/2023/07/Modern-Living-Room-Furniture-Ideas-Hero-scaled.jpg",
    },
    {
        id: 11,
        name: "Nissan Safari Spirit Type II 4WD 1997",
        price: "14.8 Lac",
        cat: "car",
        location: "Others",
        city: "Gilgit",
        imgSrc: "https://static0.topspeedimages.com/wordpress/wp-content/uploads/2022/11/1997-nissan-safari-patrol.jpg?w=1600&h=900&fit=crop",
    },
    {
        id: 12,
        name: "Samsung S25 Ultra",
        price: "450,000",
        cat: "mobile",
        location: "Nazimabad",
        city: "Karachi",
        imgSrc: "https://static0.anpoimages.com/wordpress/wp-content/uploads/wm/2025/01/samsung-galaxy-s25-ultra-hands-on-81.jpg?q=49&fit=crop&w=825&dpr=2",
    },
    {
        id: 13,
        name: "Google Pixel 10 Pro XL",
        price: "225,000",
        cat: "mobile",
        location: "Samnabad",
        city: "Lahore",
        imgSrc: "https://www.cnet.com/a/img/resize/bf232f9cb88884838de4c5350e4dfb78e18a3a28/hub/2025/08/13/e2798fcd-334b-4d06-8c61-f65eb9b57f1e/google-pixel-10-pro-xl-review-cnet-lanxon-21.jpg?auto=webp&fit=crop&height=675&width=1200",
    },
];