export const ads = [
    {
        id: 1,
        name: "IPhone X",
        price: 49000,
        cat: "mobile",
        location: "G-10",
        city: "Islamabad",
        imgSrc: "https://starcity.pk/wp-content/uploads/2022/08/Iphone-x-2-1.jpg",
    },
    {
        id: 2,
        name: "IPhone 15",
        price: 150000,
        cat: "mobile",
        location: "Touch Me Chowrangi",
        city: "Karachi",
        imgSrc: "https://static0.pocketlintimages.com/wordpress/wp-content/uploads/wm/2023/09/iphone-15-pro-max-review-4-1.jpg?w=1600&h=900&fit=crop",
    },
    {
        id: 3,
        name: "1 Kanal House DHA Phase 2",
        price: 25000000,
        cat: "house",
        location: "DHA Phase 2 Block B",
        city: "Islamabad",
        imgSrc: "https://www.livehome3d.com/assets/img/social/how-to-design-a-house.jpg",
    },
    {
        id: 4,
        name: "2 Kanal House Bahria Town Phase 3",
        price: 55000000,
        cat: "house",
        location: "Bahria Town Phase 3",
        city: "Islamabad",
        imgSrc: "https://thermohouse.ie/wp-content/uploads/2019/04/hero-image.jpg",
    },
    {
        id: 5,
        name: "2 Kanal House Bahria Town Phase 3",
        price: 108000000,
        cat: "house",
        location: "Bahria Town Phase 2",
        city: "Islamabad",
        imgSrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpui9mvz_xElG51fD0sxPOZ8EtIQzv0s2Lxw&s",
    },
    {
        id: 6,
        name: "Toyota Land Cruiser LC300 ZX 2022",
        price: 65000000,
        cat: "car",
        location: "Johar Town",
        city: "Lahore",
        imgSrc: "https://lh3.googleusercontent.com/proxy/03-8uv6kYl6g3TARb2Ied1Se05RK1K_JGJ8sO_XG2Fd-fv00YwZLTaL-ThqgJ-uR7VjMtLYEwXTnZLojPbSej4BsbL9UZX_URqG2k9biTUKlWqJdTiOHPMC-jXJvRg_rwQNjclA61RETMTe4H-xMpI34_rNneZQ02P2u-qrFrYPZR72QuVusOmg",
    },
    {
        id: 7,
        name: "Mazda RX7 Rocket Bunny",
        price: 18000000,
        cat: "car",
        location: "F-7",
        city: "Islamabad",
        imgSrc: "https://scontent.fpew3-1.fna.fbcdn.net/v/t51.75761-15/488492610_18453075934075561_6553391370000354483_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=127cfc&_nc_ohc=_EVVOtN0eakQ7kNvwHwURkN&_nc_oc=Adm3x9a0Qs5-TWeWiemVIYtULdsSEh9HSI3bK0dCcPUgWwE97Hgsklhq3BQNOSQx1ss&_nc_zt=23&_nc_ht=scontent.fpew3-1.fna&_nc_gid=Q5n8b-eqV09U1Deey5iQAQ&oh=00_Afv5j1kZRCigBSbFQvgIJOf5t8PYTvm24rC5a_dhbIsI5A&oe=698D75BA",
    },
    {
        id: 8,
        name: "Mercedes Benz E63 AMG W211",
        price: 12000000,
        cat: "car",
        location: "Bahadurabad",
        city: "Karachi",
        imgSrc: "https://i.redd.it/6vuc9wtdc11b1.jpg",
    },
    {
        id: 9,
        name: "2 Bedrooms For Rent",
        price: 64000,
        cat: "house",
        location: "Park View City",
        city: "Islamabad",
        imgSrc: "https://www.smartcitypk.com/assets/uploads/villas_5e621fbc1d250.png",
    },
    {
        id: 10,
        name: "Custom Furniture",
        price: 120000,
        cat: "furniture",
        location: "Gulshan-e-Iqbal",
        city: "Lahore",
        imgSrc: "https://birchwoodfurniture.ca/wp-content/uploads/2023/07/Modern-Living-Room-Furniture-Ideas-Hero-scaled.jpg",
    },
    {
        id: 11,
        name: "Nissan Safari Spirit Type II 4WD 1997",
        price: 1480000,
        cat: "car",
        location: "Others",
        city: "Gilgit",
        imgSrc: "https://static0.topspeedimages.com/wordpress/wp-content/uploads/2022/11/1997-nissan-safari-patrol.jpg?w=1600&h=900&fit=crop",
    },
    {
        id: 12,
        name: "Samsung S25 Ultra",
        price: 450000,
        cat: "mobile",
        location: "Nazimabad",
        city: "Karachi",
        imgSrc: "https://static0.anpoimages.com/wordpress/wp-content/uploads/wm/2025/01/samsung-galaxy-s25-ultra-hands-on-81.jpg?q=49&fit=crop&w=825&dpr=2",
    },
    {
        id: 13,
        name: "Google Pixel 10 Pro XL",
        price: 225000,
        cat: "mobile",
        location: "Samnabad",
        city: "Lahore",
        imgSrc: "https://www.cnet.com/a/img/resize/bf232f9cb88884838de4c5350e4dfb78e18a3a28/hub/2025/08/13/e2798fcd-334b-4d06-8c61-f65eb9b57f1e/google-pixel-10-pro-xl-review-cnet-lanxon-21.jpg?auto=webp&fit=crop&height=675&width=1200",
    },
    {
        id: 14,
        name: "Golden Sofa 2 Seater",
        price: 37000,
        cat: "furniture",
        location: "Westridge",
        city: "Rawalpindi",
        imgSrc: "https://i5.walmartimages.com/seo/Upholstered-2-Seater-Sofa-Comfy-Modern-Couch-Home-Living-Room-Furniture-Metal-Base-Mustard_306157c8-e426-4cbb-b8de-a9b022118cb4.4245286f05da9346757a40d94340f321.jpeg",
    },
    {
        id: 15,
        name: "6 Seater Sofa Set",
        price: 150000,
        cat: "furniture",
        location: "Iqbal Town",
        city: "Rawalpindi",
        imgSrc: "https://watanfurnitures.com/wp-content/uploads/2021/04/Watan-Furnitures-2022-475.jpg",
    },
    {
        id: 16,
        name: "King Size Bed",
        price: 88000,
        cat: "furniture",
        location: "Clifton",
        city: "Karachi",
        imgSrc: "https://homefactree.com/wp-content/uploads/2019/01/antrio-sheesham-bed-scaled.jpg",
    },
    {
        id: 17,
        name: "IPhone 12 Pro JV",
        price: 65000,
        cat: "mobile",
        location: "Others",
        city: "Lahore",
        imgSrc: "https://hf-store.pk/wp-content/uploads/2024/10/469726168_919033273653642_3904322415382956589_n.jpg",
    },
    {
        id: 18,
        name: "Mercedes Benz CLK 200",
        price: 3400000,
        cat: "car",
        location: "DHA, Phase 1",
        city: "Karahi",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/c/c0/CLK_209_%28Cabriolet%29.jpg",
    },
    {
        id: 19,
        name: "BMW M340i 2020",
        price: 15000000,
        cat: "car",
        location: "F-6",
        city: "Islamabad",
        imgSrc: "https://preview.redd.it/how-realistic-is-an-m340i-v0-vgk8gzgkin8e1.jpeg?auto=webp&s=fa4d180f71540f98e7de4349f910a38503e322f7",
    },
    {
        id: 20,
        name: "BMW M340i 2015",
        price: 8000000,
        cat: "car",
        location: "Bahria Town, Phase 8",
        city: "Lahore",
        imgSrc: "https://i.ytimg.com/vi/IhtKOwJySZo/maxresdefault.jpg",
    },
    {
        id: 21,
        name: "1 Kanal Spanish House for Sale DHA Phase 2 Islamabad",
        price: 120000000,
        cat: "house",
        location: "DHA Phase 2",
        city: "Islamabad",
        imgSrc: "https://media.zameen.com/thumbnails/88351083-800x600.jpeg",
    },
    {
        id: 22,
        name: "2 Wooden Cupboards",
        price: 55000,
        cat: "furniture",
        location: "G-11",
        city: "Islamabad",
        imgSrc: "https://www.lujoluxuryliving.com/cdn/shop/files/Image_5.jpg?crop=center&height=1200&v=1747656940&width=1200",
    },
    {
        id: 23,
        name: "Samsung Galaxy A07",
        price: 39999,
        cat: "mobile",
        location: "Others",
        city: "Faisalabad",
        imgSrc: "https://pctechmag.com/wp-content/uploads/2025/12/Samsung-Galaxy-A07-blue.jpg",
    },
    {
        id: 24,
        name: "IPhone 8 PTA Approved",
        price: 22000,
        cat: "mobile",
        location: "Others",
        city: "Lahore",
        imgSrc: "https://www.cnet.com/a/img/hub/2017/09/18/3b8ba412-daab-41f5-bafe-c993413f98ff/iphone-8-34.jpg",
    },
    {
        id: 25,
        name: "Google Pixel 5",
        price: 35000,
        cat: "mobile",
        location: "Johar Town",
        city: "Lahore",
        imgSrc: "https://techbuzzireland.com/wp-content/uploads/2020/10/unnamed-2-1.jpg",
    },
    {
        id: 26,
        name: "Google Pixel 5, 6, 7",
        price: 60000,
        cat: "mobile",
        location: "Samnabad",
        city: "Lahore",
        imgSrc: "https://www.computerworld.com/wp-content/uploads/2024/03/google-pixel-7-vs-other-pixels-upgrade-100933379-orig.jpg?quality=50&strip=all",
    },
    {
        id: 27,
        name: "Google Pixel 5, 6, 7",
        price: 60000,
        cat: "mobile",
        location: "Samnabad",
        city: "Lahore",
        imgSrc: "https://www.computerworld.com/wp-content/uploads/2024/03/google-pixel-7-vs-other-pixels-upgrade-100933379-orig.jpg?quality=50&strip=all",
    },
    {
        id: 28,
        name: "Google Pixel 5, 6, 7",
        price: 60000,
        cat: "mobile",
        location: "Samnabad",
        city: "Lahore",
        imgSrc: "https://www.computerworld.com/wp-content/uploads/2024/03/google-pixel-7-vs-other-pixels-upgrade-100933379-orig.jpg?quality=50&strip=all",
    },
    {
        id: 29,
        name: "Nissan Silvia s15",
        price: 12500000,
        cat: "car",
        location: "Saddar",
        city: "Rawalpindi",
        imgSrc: "https://garage-defend.com/uploads/cars/04-22/efscturiGww2lYfEqLS8nnaoe7786AwVDQ6ne3Mu.jpeg",
    },
    {
        id: 30,
        name: "Nissan Z350",
        price: 15500000,
        cat: "car",
        location: "Others",
        city: "Karachi",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/2/2c/2004_Nissan_350Z_3.5_Front.jpg",
    },
    {
        id: 31,
        name: "1 Kanal Spanish House for Sale DHA Phase 2 Islamabad",
        price: 120000000,
        cat: "house",
        location: "DHA Phase 2",
        city: "Lahore",
        imgSrc: "https://media.zameen.com/thumbnails/88351083-800x600.jpeg",
    },
    {
        id: 32,
        name: "1 Kanal Spanish House for Sale DHA Phase 2 Islamabad",
        price: 120000000,
        cat: "house",
        location: "DHA Phase 2",
        city: "Islamabad",
        imgSrc: "https://media.zameen.com/thumbnails/88351083-800x600.jpeg",
    },
    {
        id: 33,
        name: "1 Kanal Spanish House for Sale DHA Phase 2 Islamabad",
        price: 120000000,
        cat: "house",
        location: "DHA Phase 2",
        city: "Islamabad",
        imgSrc: "https://media.zameen.com/thumbnails/88351083-800x600.jpeg",
    },
    {
        id: 34,
        name: "1 Kanal Spanish House for Sale DHA Phase 2 Islamabad",
        price: 120000000,
        cat: "house",
        location: "DHA Phase 2",
        city: "Karachi",
        imgSrc: "https://media.zameen.com/thumbnails/88351083-800x600.jpeg",
    },
    {
        id: 35,
        name: "Custom Furniture",
        price: 120000,
        cat: "furniture",
        location: "Gulshan-e-Iqbal",
        city: "Lahore",
        imgSrc: "https://birchwoodfurniture.ca/wp-content/uploads/2023/07/Modern-Living-Room-Furniture-Ideas-Hero-scaled.jpg",
    },
    {
        id: 36,
        name: "Custom Furniture",
        price: 120000,
        cat: "furniture",
        location: "Gulshan-e-Iqbal",
        city: "Lahore",
        imgSrc: "https://birchwoodfurniture.ca/wp-content/uploads/2023/07/Modern-Living-Room-Furniture-Ideas-Hero-scaled.jpg",
    },
    {
        id: 37,
        name: "Custom Furniture",
        price: 120000,
        cat: "furniture",
        location: "Gulshan-e-Iqbal",
        city: "Lahore",
        imgSrc: "https://birchwoodfurniture.ca/wp-content/uploads/2023/07/Modern-Living-Room-Furniture-Ideas-Hero-scaled.jpg",
    },
];

//Price Formatter
export function formatPricePKR(price) {
  if (price >= 1e7) return "Rs " + (price / 1e7).toFixed(2) + " Cr";
  if (price >= 1e5) return "Rs " + (price / 1e5).toFixed(2) + " Lakh";
  return "Rs " + price.toLocaleString("en-PK");
};

//backToTop Toggle Button
export function initBackToTop(btnId, showAfter = 200) {
    const btn = document.getElementById(btnId);
    if(!btn) {return}
    window.addEventListener("scroll",()=>{
        btn.style.display = window.scrollY > showAfter ? "flex" : "none";
    });
    btn.addEventListener("click",()=>{
        window.scrollTo({top: 0, behavior: "smooth"});
    });
}